const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const CREATE_STREAM = 'CREATE_STREAM';
const FETCH_STREAMS = 'FETCH_STREAMS';
const FETCH_STREAM = 'FETCH_STREAM';
const DELETE_STREAM = 'DELETE_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';

const actionTypes = {
  SIGN_IN: SIGN_IN,
  SIGN_OUT: SIGN_OUT,
  CREATE_STREAM: CREATE_STREAM,
  FETCH_STREAMS: FETCH_STREAMS,
  FETCH_STREAM: FETCH_STREAM,
  DELETE_STREAM: DELETE_STREAM,
  EDIT_STREAM: EDIT_STREAM
}

export default actionTypes;